# Default values for skydns.
# This is a YAML-formatted file
replicas: 1
version: v11
color: FFFF66
k8sapp: kube-dns
etcd_image: "gcr.io/google_containers/etcd:2.2.1"
etcd_cpu: 100m
etcd_mem: 500Mi
etcd_listen_urls: "http://127.0.0.1:2379,http://127.0.0.1:4001"
etcd_advertise_urls: "http://127.0.0.1:2379,http://127.0.0.1:4001"
etcd_cluster_token: skydns-etcd
kubesky_cpu: 100m
kubesky_mem: 200Mi
kubesky_image: "gcr.io/google_containers/kube2sky:1.14"
skydns_cpu: 100m
skydns_mem: 200Mi
skydns_machines: "http://127.0.0.1:4001"
skydns_address: 0.0.0.0
skydns_port: 53
skydns_image: "gcr.io/google_containers/skydns:2015-10-13-8c72f8c"
healthz_cpu: 10m
healthz_mem: 20Mi
healthz_image: "gcr.io/google_containers/exechealthz:1.0"
healthz_port: 8080
healthz_delay: 60
healthz_timeout: 5
healthz_success_thresh: 1
healthz_failure_thresh: 5
readiness_port: 8081
readiness_delay: 30
readiness_timeout: 5
dns_domain: cluster.local
cluster_ip: 10.100.0.10