apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    name: {{.Chart.Name}}
    kubernetes.io/cluster-service: "true"
  name: {{.Chart.Name}}
  namespace: "kube-system"
spec:
    type: "LoadBalancer"
    ports:
      -
        port: 80
        targetPort: 8289
    selector:
      name: "kubedash"