apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1
  name: heapster-v1
  namespace: default
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v1
  template:
    metadata:
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes:https://kubernetes?apiVersion=v1&insecure=true&inClusterConfig=false
        - --sink=influxdb:http://influxdb:8086?avoidColumns=true
        - --poll_duration=10s
        - --stats_resolution=5s
        image: gcr.io/google_containers/heapster:v0.15.0
        imagePullPolicy: IfNotPresent
        name: heapster
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs
