apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    name: prometheus
  template:
    metadata:
      labels:
        kubernetes.io/color: E5CCFF
        name: prometheus
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: sqlite3:/promdash/file.sqlite3
        image: quay.io/samsung_ag/promdash:latest
        imagePullPolicy: Always
        name: promdash
        ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /promdash
          name: data
      - args:
        - -t
        - PROMETHEUS,KUBE_APISERVER,KUBE_CONTROLLER,KUBE_SCHEDULER,APISERVER_ETCD,KUBE_ETCD,APISERVER_CADVISOR,ETCD_CADVISOR
        - -d
        - /var/prometheus
        - -K
        env:
        - name: PROMETHEUS_TARGET_ADDRESS
          value: localhost:9090
        - name: KUBE_APISERVER_TARGET_ADDRESS
          value: localhost:8001
        - name: KUBE_CONTROLLER_TARGET_ADDRESS
          value: $KUBE_CONTROLLER_IP:10252
        - name: KUBE_SCHEDULER_TARGET_ADDRESS
          value: $KUBE_SCHEDULER_IP:10251
        - name: APISERVER_ETCD_TARGET_ADDRESS
          value: $KUBE_APISERVER_IP:4001
        - name: KUBE_ETCD_TARGET_ADDRESS
          value: $KUBE_ETCD_IP:4001
        - name: APISERVER_CADVISOR_TARGET_ADDRESS
          value: $KUBE_APISERVER_IP:8094
        - name: ETCD_CADVISOR_TARGET_ADDRESS
          value: $KUBE_ETCD_IP:8094
        image: quay.io/samsung_ag/prometheus:latest
        imagePullPolicy: Always
        name: prometheus
        ports:
        - containerPort: 9090
          hostPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: /var/prometheus/
          name: data
      - args:
        - proxy
        - --port=8001
        - --api-prefix=/
        - --server=https://kubernetes
        - --insecure-skip-tls-verify=true
        - --api-version=v1
        - --logtostderr=true
        - --v=2
        image: gcr.io/google_containers/kubectl:v0.18.0-350-gfb3305edcf6c1a
        imagePullPolicy: IfNotPresent
        name: kubectl-proxy
      dnsPolicy: ClusterFirst
      nodeSelector:
        kraken-node: node-01
      restartPolicy: Always
      volumes:
      - name: data 
        emptyDir: {}
