apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: default
spec:
  ports:
  - name: prometheus
    nodePort: 30090
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: promdash
    nodePort: 30091
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: prometheus
  sessionAffinity: None
  type: NodePort
