apiVersion: v1
kind: Service
metadata:
  labels:
    name: podpincher
  name: podpincher
  namespace: default
spec:
  deprecatedPublicIPs:
  - 172.16.1.103
  ports:
  - port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    name: podpincher
  sessionAffinity: None
  type: ClusterIP
