apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: Grafana
    kubernetes.io/cluster-service: "true"
    version: v1
  name: grafana-v1
  namespace: default
spec:
  replicas: 1
  selector:
    k8s-app: Grafana
    version: v1
  template:
    metadata:
      labels:
        k8s-app: Grafana
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - env:
        - name: GRAFANA_DEFAULT_DASHBOARD
          value: /dashboard/file/loadtest.json
        - name: INFLUXDB_EXTERNAL_URL
          value: http://$INFLUXDB_EXTERNAL_HOST:8086/db/
        - name: INFLUXDB_HOST
          value: influxdb
        - name: INFLUXDB_PORT
          value: "8086"
        image: quay.io/samsung_ag/grafana:latest
        imagePullPolicy: Always
        name: grafana
      dnsPolicy: ClusterFirst
      restartPolicy: Always
