apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Grafana
  name: grafana
  namespace: default
spec:
  deprecatedPublicIPs:
  - $GRAFANA_PUBLIC_IP
  ports:
  - nodePort: 0
    port: 8002
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: Grafana
  sessionAffinity: None
  type: ClusterIP
