apiVersion: v1beta3
kind: Service
metadata:
  name: heapster
  namespace: default
  labels:
    k8s-app: Heapster
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    k8s-app: Heapster
  publicIPs:
    - "$HEAPSTER_PUBLIC_IP"
