apiVersion: v1beta3
kind: Service
metadata:
  name: influxdb
  namespace: default
  labels:
    k8s-app: InfluxDB
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: InfluxDB
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: api
      port: 8086
      targetPort: 8086
  selector:
    k8s-app: InfluxDB
  publicIPs:
    - $INFLUXDB_PUBLIC_IP
