apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: InfluxDB
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: InfluxDB
  name: influxdb
  namespace: default
spec:
  deprecatedPublicIPs:
  - $INFLUXDB_PUBLIC_IP
  ports:
  - name: http
    nodePort: 0
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: api
    nodePort: 0
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    k8s-app: InfluxDB
  sessionAffinity: None
  type: ClusterIP
