apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: influxdb-v1
  namespace: default
  labels:
    k8s-app: InfluxDB
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: InfluxDB
    version: v1
  template:
    metadata:
      labels:
        k8s-app: InfluxDB
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: quay.io/samsung_ag/influxdb:stable
          name: influxdb
          ports:
            - containerPort: 8083
              hostPort: 8083
            - containerPort: 8086
              hostPort: 8086
          env:
            - name: INFLUXDB_INIT_PWD
              value: root
            - name: PRE_CREATE_DB
              value: k8s;grafana 
      nodeSelector:
        kraken-node: node-01
