# based on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: kube-dns-v3
    kubernetes.io/cluster-service: "true"
  name: kube-dns-v3
  namespace: default
spec:
  replicas: 3
  selector:
    k8s-app: kube-dns
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v2.0.9
          # command: "/etcd"
          args:
            - -listen-client-urls
            - http://127.0.0.1:2379,http://127.0.0.1:4001
            - -advertise-client-urls
            - http://127.0.0.1:2379,http://127.0.0.1:4001
            - -initial-cluster-token
            - skydns-etcd
        - name: kube2sky
          image: gcr.io/google_containers/kube2sky:1.9
          # command: "/kube2sky"
          args:
            - -domain=$CLUSTER_DOMAIN
            - -kube_master_url=$KUBE_MASTER_URL
            # - -kubecfg_file=/etc/dns_token/kubeconfig
          # volumeMounts:
          # - mountPath: /etc/dns_token
            # name: dns-token
            # readOnly: true
        - name: skydns
          image: gcr.io/google_containers/skydns:2015-03-11-001
          # command: "/skydns"
          args:
            - -machines=http://localhost:4001
            - -addr=0.0.0.0:53
            - -domain=$CLUSTER_DOMAIN.
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nslookup kubernetes.default.$CLUSTER_DOMAIN localhost >/dev/null
            initialDelaySeconds: 30
            timeoutSeconds: 5
      dnsPolicy: Default  # Don't use cluster DNS.
      # volumes:
      # - name: dns-token
        # secret:
          # secretName: token-system-dns
