apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: framework
  name: framework
  namespace: default
spec:
  replicas: 10
  selector:
    name: framework
  template:
    metadata:
      labels:
        name: framework
    spec:
      containers:
      - image: quay.io/samsung_ag/trogdor-framework:latest
        imagePullPolicy: Always
        name: framework
        ports:
        - containerPort: 9080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
