apiVersion: v1
kind: ReplicationController
metadata:
  name: pause
  namespace: default
spec:
  replicas: 10
  selector:
    name: pause
  template:
    metadata:
      labels:
        name: pause
    spec:
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:2.0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
