apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pause
  name: pause
  namespace: default
spec:
  replicas: 10
  selector:
    name: pause
  template:
    metadata:
      labels:
        name: pause
        kubernetes.io/color: "444444"
    spec:
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:2.0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pause
    kubernetes.io/name: "Pause"
  name: pause
  namespace: default
spec:
  ports:
  - name: pause
    port: 80
  selector:
    name: pause
  sessionAffinity: None
  type: ClusterIP
