---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-generator-master
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: load-generator-master
    spec:
      containers:
      - command:
        - locust
        - -f
        - /scripts/locustfile.py
        - --master
        - --host=http://framework:9080
        image: quay.io/spiffxp/trogdor-load-generator:latest
        imagePullPolicy: Always
        name: load-generator-master
        ports:
        - containerPort: 8089
          protocol: TCP
        - containerPort: 5557
          protocol: TCP
        - containerPort: 5558
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Locust
    name: load-generator-master
  name: load-generator-master
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30340
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: slavecomm
    nodePort: 30341
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: slavecomm2
    nodePort: 30342
    port: 5558
    protocol: TCP
    targetPort: 5558
  selector:
    name: load-generator-master
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-generator-slave
  namespace: default
spec:
  replicas: 6
  template:
    metadata:
      labels:
        name: load-generator-slave
    spec:
      containers:
      - command:
        - locust
        - -f
        - /scripts/locustfile.py
        - --slave
        - --master-host=load-generator-master
        - --host=http://framework:9080
        image: quay.io/spiffxp/trogdor-load-generator:latest
        imagePullPolicy: Always
        name: load-generator-slave

