apiVersion: v1
kind: ReplicationController
metadata:
  name: ranchervm
spec:
  replicas: 2
  selector:
    app: ranchervm
  template:
    metadata:
      name: ranchervm
      labels:
        app: ranchervm
    spec:
      containers:
        - name: ranchervm
          image: rancher/ranchervm
          resources:
            requests:
              cpu: "1024m"
              memory: "1Gi"
            limits:
              cpu: "1024m"
              memory: "1Gi"
          securityContext:
              privileged: false
